name: Java CI with Tests and Code Scanning

on:
  # Trigger bei jedem Push und Pull Request
  push:
    branches:
      - '*'    # Alle Branches
  pull_request:
    branches:
      - '*'    # Alle Branches

jobs:
  # Job 1: Tests ausführen
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test

  # Job 2: Code Scanning mit CodeQL
  code_scanning:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2